apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/pipeline
  ref:
    branch: FILLED_IN_BY_BIOMAGE_STAGE
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-59-merge-*-pipeline-runner
spec:
  releaseName: ""
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline
        namespace: pipeline-STAGING_SANDBOX_ID
  valuesFrom:
    - kind: ConfigMap
      valuesKey: account-config.yaml
      name: account-config
      optional: false
  values:
    clusterEnv: staging
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-59-merge-002da24e866460dc2aa146d33714666530dc6dbf-pipeline-runner
    sandboxId: STAGING_SANDBOX_ID
    memoryRequest: 4Gi
    replicaCount: 0
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-STAGING_SANDBOX_ID
