apiVersion: v1
kind: Namespace
metadata:
  name: ui-agi-test-flux
  labels:
    sandboxId: agi-test-flux
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui
  namespace: ui-agi-test-flux
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-agi-test-flux
  labels:
    sandboxId: agi-test-flux
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-87-merge-*
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui
        namespace: ui-agi-test-flux
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: [echo, '0']
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/ui
      sandboxId: agi-test-flux
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-87-merge-a9f8c952973c40f4e86ec95d20a519170b1bc351-1669203442
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
    # filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-agi-test-flux
  labels:
    sandboxId: agi-test-flux
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api-chart
  namespace: api-agi-test-flux
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: api
  namespace: api-agi-test-flux
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/api
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: api
  namespace: api-agi-test-flux
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-pull-39-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-agi-test-flux
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux CI/CD
        email: ci@biomage.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-agi-test-flux
  labels:
    sandboxId: agi-test-flux
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api-chart
        namespace: api-agi-test-flux
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/api
      sandboxId: agi-test-flux
      rdsSandboxId: default
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-39-merge-9b7cd99a5569a31be4d4eac2d343bf0c9988ffd3-1669215005 # {"$imagepolicy": "api-agi-test-flux:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-agi-test-flux
  labels:
    sandboxId: agi-test-flux
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker
  namespace: worker-agi-test-flux
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/worker
  ref:
    branch: flux-v2-migration
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-agi-test-flux
  annotations:
    filter.fluxcd.io/r: glob:refs-pull-41-merge-*-r
    filter.fluxcd.io/python: glob:refs-pull-41-merge-*-python
  labels:
    sandboxId: agi-test-flux
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker
        namespace: worker-agi-test-flux
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
  values:
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    sandboxId: agi-test-flux
    replicaCount: 0
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-41-merge-caea44ee599ed32b7ba473b87f539c66ae3db98e-r
      memoryRequest: 4Gi
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-41-merge-caea44ee599ed32b7ba473b87f539c66ae3db98e-python
    datadogTags: kube_namespace:worker-agi-test-flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-agi-test-flux
  labels:
    sandboxId: agi-test-flux
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline
  namespace: pipeline-agi-test-flux
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/pipeline
  ref:
    branch: flux-v2-migration
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-agi-test-flux
  labels:
    sandboxId: agi-test-flux
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-59-merge-*-pipeline-runner
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline
        namespace: pipeline-agi-test-flux
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
  values:
    clusterEnv: staging
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-59-merge-bfa18a077865efbc0131d9c6593b057ad281f473-pipeline-runner
    sandboxId: agi-test-flux
    memoryRequest: 4Gi
    replicaCount: 0
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-agi-test-flux
