apiVersion: v1
kind: Namespace
metadata:
  name: api-agi-ui87
  labels:
    sandboxId: agi-ui87
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api
  namespace: api-agi-ui87
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    commit: d48106e8f8eb89cccb1b1afc182e2c11d4d58d53
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: api
  namespace: api-agi-ui87
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/api
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: api
  namespace: api-agi-ui87
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-agi-ui87
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-agi-ui87
  labels:
    sandboxId: agi-ui87
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api
        namespace: api-agi-ui87
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/api
      sandboxId: agi-ui87
      rdsSandboxId: default
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-9d3ab88d09f2bf0b033484ed04d051b23c5582e2 # {"$imagepolicy": "api-agi-ui87:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-agi-ui87
  labels:
    sandboxId: agi-ui87
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker
  namespace: worker-agi-ui87
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/worker
  ref:
    commit: 3c6c3ce43acbff2ffde76b9e82db24bf40a318e0
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-agi-ui87
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-agi-ui87
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-r$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-agi-ui87
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-python$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-agi-ui87
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-agi-ui87
  labels:
    sandboxId: agi-ui87
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker
        namespace: worker-agi-ui87
  values:
    sandboxId: agi-ui87
    replicaCount: 0
    r:
      image:
        registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-f59a99d4b9fd0c46465540398eca680bcd1f6462-r # {"$imagepolicy": "worker-agi-ui87:worker-r:tag"}
      memoryRequest: 4Gi
    python:
      image:
        registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-f59a99d4b9fd0c46465540398eca680bcd1f6462-python # {"$imagepolicy": "worker-agi-ui87:worker-python:tag"}
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    datadogTags: kube_namespace:worker-agi-ui87
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-agi-ui87
  labels:
    sandboxId: agi-ui87
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline
  namespace: pipeline-agi-ui87
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/pipeline
  ref:
    commit: c24494bb73d6824c1845c8965fbc52c4d823103f
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-agi-ui87
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-agi-ui87
spec:
  imageRepositoryRef:
    name: pipeline
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-agi-ui87
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-agi-ui87
  labels:
    sandboxId: agi-ui87
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline
        namespace: pipeline-agi-ui87
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: agi-ui87
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: pipeline
      tag: refs-heads-master-1cbee9272c22e474742ac4162fae9db40fb37f2b-pipeline-runner # {"$imagepolicy": "pipeline-agi-ui87:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-agi-ui87
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
