apiVersion: v1
kind: Namespace
metadata:
  name: ui-agi-pipeline59
  labels:
    sandboxId: agi-pipeline59
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui
  namespace: ui-agi-pipeline59
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: ui
  namespace: ui-agi-pipeline59
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/ui
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ui
  namespace: ui-agi-pipeline59
spec:
  imageRepositoryRef:
    name: ui
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ui-image-update
  namespace: ui-agi-pipeline59
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - UI image update
        email: ci@biomage.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-agi-pipeline59
  labels:
    sandboxId: agi-pipeline59
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui
        namespace: ui-agi-pipeline59
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: [echo, '0']
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/ui
      sandboxId: agi-pipeline59
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-27f262ea4513d9e83c7e605f384999b0acbd9846 # {"$imagepolicy": "ui-agi-pipeline59:ui:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
    # filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-agi-pipeline59
  labels:
    sandboxId: agi-pipeline59
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api
  namespace: api-agi-pipeline59
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: api
  namespace: api-agi-pipeline59
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/api
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: api
  namespace: api-agi-pipeline59
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-agi-pipeline59
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-agi-pipeline59
  labels:
    sandboxId: agi-pipeline59
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api
        namespace: api-agi-pipeline59
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/api
      sandboxId: agi-pipeline59
      rdsSandboxId: default
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-c568afaac6ca4fdca16c6a426e215a403588db13-2 # {"$imagepolicy": "api-agi-pipeline59:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-agi-pipeline59
  labels:
    sandboxId: agi-pipeline59
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker
  namespace: worker-agi-pipeline59
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/worker
  ref:
    branch: FILLED_IN_BY_BIOMAGE_STAGE
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-agi-pipeline59
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-agi-pipeline59
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-r$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-agi-pipeline59
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-python$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-agi-pipeline59
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-agi-pipeline59
  labels:
    sandboxId: agi-pipeline59
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker
        namespace: worker-agi-pipeline59
  values:
    sandboxId: agi-pipeline59
    replicaCount: 0
    r:
      image:
        registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-f59a99d4b9fd0c46465540398eca680bcd1f6462-r # {"$imagepolicy": "worker-agi-pipeline59:worker-r:tag"}
      memoryRequest: 4Gi
    python:
      image:
        registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-f59a99d4b9fd0c46465540398eca680bcd1f6462-python # {"$imagepolicy": "worker-agi-pipeline59:worker-python:tag"}
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    datadogTags: kube_namespace:worker-agi-pipeline59
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-agi-pipeline59
  labels:
    sandboxId: agi-pipeline59
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline-chart
  namespace: pipeline-agi-pipeline59
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/pipeline
  ref:
    branch: FILLED_IN_BY_BIOMAGE_STAGE
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-agi-pipeline59
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-agi-pipeline59
spec:
  imageRepositoryRef:
    name: pipeline
  filterTags:
    pattern: ^refs-pull-59-merge-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-agi-pipeline59
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-agi-pipeline59
  labels:
    sandboxId: agi-pipeline59
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline-chart
        namespace: pipeline-agi-pipeline59
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: agi-pipeline59
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: pipeline
      tag: refs-pull-59-merge-cbd8cf3be3d01fbb9cea5b73171b5872ecddc8b1-pipeline-runner-1669641552 # {"$imagepolicy": "pipeline-agi-pipeline59:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-agi-pipeline59
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
