apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-flux-test
  name: ui-agi-flux-test
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui
  namespace: ui-agi-flux-test
spec:
  interval: 10m0s
  ref:
    branch: FILLED_IN_BY_CI
    commit: bd2d5a37a43cf670e0e7ea23fd40f375896f0b7d
  url: https://github.com/biomage-org/iac
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-87-merge-*
  labels:
    sandboxId: agi-flux-test
  name: ui
  namespace: ui-agi-flux-test
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui
        namespace: ui-agi-flux-test
  values:
    biomageCi:
      repo: biomage-org/ui
      sandboxId: agi-flux-test
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-87-merge-b0664f89f23cb6289f1b1e4598b04a7bc48ad19a
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    service:
      additionalHosts: false
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
    - kind: ConfigMap
      valuesKey: account-config.yaml
      name: account-config
      optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-flux-test
  name: api-agi-flux-test
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api
  namespace: api-agi-flux-test
spec:
  interval: 10m0s
  ref:
    commit: bd2d5a37a43cf670e0e7ea23fd40f375896f0b7d
  url: https://github.com/biomage-org/iac
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-39-merge-*
  labels:
    sandboxId: agi-flux-test
  name: api
  namespace: api-agi-flux-test
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api
        namespace: api-agi-flux-test
  values:
    biomageCi:
      rdsSandboxId: default
      repo: biomage-org/api
      sandboxId: agi-flux-test
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-39-merge-9531769856dda964c40f9e61f36b314d2a0a5996
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v2/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v2/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
    - kind: ConfigMap
      valuesKey: account-config.yaml
      name: account-config
      optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-flux-test
  name: worker-agi-flux-test
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker
  namespace: worker-agi-flux-test
spec:
  interval: 10m0s
  ref:
    branch: FILLED_IN_BY_CI
    commit: 3214f05832ef0aaf946ba41d452714cc2464e128
  url: https://github.com/biomage-org/worker
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-pull-41-merge-*-python
    filter.fluxcd.io/r: glob:refs-pull-41-merge-*-r
  labels:
    sandboxId: agi-flux-test
  name: worker
  namespace: worker-agi-flux-test
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker
        namespace: worker-agi-flux-test
  values:
    datadogTags: kube_namespace:worker-agi-flux-test
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-41-merge-3214f05832ef0aaf946ba41d452714cc2464e128-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-41-merge-3214f05832ef0aaf946ba41d452714cc2464e128-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: agi-flux-test
    serviceAccount:
      iamRole: worker-role-staging
  valuesFrom:
    - kind: ConfigMap
      valuesKey: account-config.yaml
      name: account-config
      optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-flux-test
  name: pipeline-agi-flux-test
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline
  namespace: pipeline-agi-flux-test
spec:
  interval: 10m0s
  ref:
    commit: d7a4950c86c76bf79a8b63b1e08170f202326f27
  url: https://github.com/biomage-org/pipeline
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-59-merge-*-pipeline-runner
  labels:
    sandboxId: agi-flux-test
  name: pipeline
  namespace: pipeline-agi-flux-test
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline
        namespace: pipeline-agi-flux-test
  values:
    clusterEnv: staging
    datadogTags: kube_namespace:pipeline-agi-flux-test
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-59-merge-d7a4950c86c76bf79a8b63b1e08170f202326f27-pipeline-runner
    replicaCount: 0
    sandboxId: agi-flux-test
    serviceAccount:
      iamRole: pipeline-role-staging
  valuesFrom:
    - kind: ConfigMap
      valuesKey: account-config.yaml
      name: account-config
      optional: false
