apiVersion: v1
kind: Namespace
metadata:
  name: ui-agi-worker41
  labels:
    sandboxId: agi-worker41
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui
  namespace: ui-agi-worker41
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    commit: e1fe37e6b83ce0541871f0284ca3ee11e4e5cdde
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: ui
  namespace: ui-agi-worker41
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/ui
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ui
  namespace: ui-agi-worker41
spec:
  imageRepositoryRef:
    name: ui
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ui-image-update
  namespace: ui-agi-worker41
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - UI image update
        email: ci@biomage.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-agi-worker41
  labels:
    sandboxId: agi-worker41
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui
        namespace: ui-agi-worker41
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: [echo, '0']
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/ui
      sandboxId: agi-worker41
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-9b74e377fd88afc1600c23734d7e2549d5d96ac3-2 # {"$imagepolicy": "ui-agi-worker41:ui:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
    # filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-agi-worker41
  labels:
    sandboxId: agi-worker41
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api
  namespace: api-agi-worker41
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    commit: e1fe37e6b83ce0541871f0284ca3ee11e4e5cdde
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: api
  namespace: api-agi-worker41
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/api
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: api
  namespace: api-agi-worker41
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-agi-worker41
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-agi-worker41
  labels:
    sandboxId: agi-worker41
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api
        namespace: api-agi-worker41
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/api
      sandboxId: agi-worker41
      rdsSandboxId: default
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-c568afaac6ca4fdca16c6a426e215a403588db13-2 # {"$imagepolicy": "api-agi-worker41:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-agi-worker41
  labels:
    sandboxId: agi-worker41
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker-chart
  namespace: worker-agi-worker41
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/worker
  ref:
    branch: flux-v2-migration
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-agi-worker41
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-agi-worker41
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-pull-41-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)-r$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-agi-worker41
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-pull-41-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)-python$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-agi-worker41
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-agi-worker41
  labels:
    sandboxId: agi-worker41
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker-chart
        namespace: worker-agi-worker41
  values:
    sandboxId: agi-worker41
    replicaCount: 0
    r:
      image:
        registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
        repository: worker
        tag: refs-pull-41-merge-95f9c39cbcd78d8dd412b585fbfe536a1c9cfcde-1669641548-r # {"$imagepolicy": "worker-agi-worker41:worker-r:tag"}
      memoryRequest: 4Gi
    python:
      image:
        registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
        repository: worker
        tag: refs-pull-41-merge-95f9c39cbcd78d8dd412b585fbfe536a1c9cfcde-1669641548-python # {"$imagepolicy": "worker-agi-worker41:worker-python:tag"}
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    datadogTags: kube_namespace:worker-agi-worker41
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-agi-worker41
  labels:
    sandboxId: agi-worker41
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline
  namespace: pipeline-agi-worker41
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/pipeline
  ref:
    commit: 0c2cdc669ba026b14729a41a15723a387d5aee7d
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-agi-worker41
spec:
  image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline
  interval: 2m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-agi-worker41
spec:
  imageRepositoryRef:
    name: pipeline
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-agi-worker41
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-agi-worker41
  labels:
    sandboxId: agi-worker41
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline
        namespace: pipeline-agi-worker41
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: agi-worker41
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: pipeline
      tag: refs-heads-master-1cbee9272c22e474742ac4162fae9db40fb37f2b-pipeline-runner # {"$imagepolicy": "pipeline-agi-worker41:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-agi-worker41
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
