apiVersion: v1
kind: Namespace
metadata:
  name: api-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api
  namespace: api-STAGING_SANDBOX_ID
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: STAGING_CHART_REF
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-39-merge-*
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api
        namespace: api-STAGING_SANDBOX_ID
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v2/health"
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: "100m"
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: "/v2/health"
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/api
      sandboxId: STAGING_SANDBOX_ID
      rdsSandboxId: STAGING_RDS_SANDBOX_ID
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-39-merge-22bb7fff7b844f2f26d56cdffbcd492700e3f93e
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
    - kind: ConfigMap
      name: account-config
      valuesKey: account-config.yaml
      optional: false
  # filled in by CI. do not modify.
