apiVersion: v1
kind: Namespace
metadata:
  name: ui-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui
  namespace: ui-STAGING_SANDBOX_ID
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: "master"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-87-merge-*
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui
        namespace: ui-STAGING_SANDBOX_ID
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: ["echo", "0"]
    loadBalancerHealthCheck:
      path: "/robots.txt"
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/ui
      sandboxId: STAGING_SANDBOX_ID
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-87-merge-a9f8c952973c40f4e86ec95d20a519170b1bc351-1669203442
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
    - kind: ConfigMap
      name: account-config
      valuesKey: account-config.yaml
      optional: false
      # filled in by CI. do not modify.
