apiVersion: v1
kind: Namespace
metadata:
  name: ui-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui
  namespace: ui-STAGING_SANDBOX_ID
spec:
  interval: 10m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: STAGING_CHART_REF
  values:
    service:
      additionalHosts: false
---
apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-87-merge-*
spec:
  releaseName: ui
  interval: 2m0s
  chart: charts/nodejs
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: ["echo", "0"]
    loadBalancerHealthCheck:
      path: "/robots.txt"
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: FILLED_IN_BY_CI
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/ui
      sandboxId: STAGING_SANDBOX_ID
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-87-merge-551631bee7d6ccd57ab207fc8297d11ce97434c8
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
      # filled in by CI. do not modify.
