apiVersion: v1
kind: Namespace
metadata:
  name: ui-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui
  namespace: ui-STAGING_SANDBOX_ID
spec:
  interval: 10m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: STAGING_CHART_REF
  values:
    service:
      additionalHosts: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-87-merge-*
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart:
        sourceRef:
          name: ui
          namespace: ui-STAGING_SANDBOX_ID
      sourceRef:
        kind: GitRepository
        name: FILLED_IN_BY_CI
        namespace: FILLED_IN_BY_CI
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: ["echo", "0"]
    loadBalancerHealthCheck:
      path: "/robots.txt"
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: FILLED_IN_BY_CI
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-org/ui
      sandboxId: STAGING_SANDBOX_ID
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-87-merge-8106669a5e9b273c418ecf4652f73791a96f4257
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
    - kind: ConfigMap
      name: account-config
      namespace: ui-STAGING_SANDBOX_ID
      key: account-config.yaml
      # filled in by CI. do not modify.
