apiVersion: v1
kind: Namespace
metadata:
  name: worker-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker
  namespace: worker-STAGING_SANDBOX_ID
spec:
  interval: 10m0s
  url: https://github.com/biomage-org/worker
  ref:
    branch: FILLED_IN_BY_CI
    commit: STAGING_CHART_REF
---
apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-STAGING_SANDBOX_ID
  annotations:
    filter.fluxcd.io/r: glob:refs-pull-41-merge-*-r
    filter.fluxcd.io/python: glob:refs-pull-41-merge-*-python
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: worker
  intarval: 2m0s
  chart: chart-infra/
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
  values:
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    sandboxId: STAGING_SANDBOX_ID
    replicaCount: 0
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-41-merge-3214f05832ef0aaf946ba41d452714cc2464e128-r
      memoryRequest: 4Gi
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-41-merge-3214f05832ef0aaf946ba41d452714cc2464e128-python
    datadogTags: kube_namespace:worker-STAGING_SANDBOX_ID
