apiVersion: v1
kind: Namespace
metadata:
  name: worker-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker
  namespace: worker-STAGING_SANDBOX_ID
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/worker
  ref:
    branch: "master"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-STAGING_SANDBOX_ID
  annotations:
    filter.fluxcd.io/r: glob:refs-pull-41-merge-*-r
    filter.fluxcd.io/python: glob:refs-pull-41-merge-*-python
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker
        namespace: worker-STAGING_SANDBOX_ID
  valuesFrom:
    - kind: ConfigMap
      valuesKey: account-config.yaml
      name: account-config
      optional: false
  values:
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    sandboxId: STAGING_SANDBOX_ID
    replicaCount: 0
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-41-merge-f998378be832b48e7465d45b198a08f1cc9b6ab4-r
      memoryRequest: 4Gi
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-41-merge-f998378be832b48e7465d45b198a08f1cc9b6ab4-python
    datadogTags: kube_namespace:worker-STAGING_SANDBOX_ID
